name: Clear all Github actions caches on sundays
on:
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-latest
    permissions: 
      actions: write

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'false'
          github-token: ${{ secrets.GITHUB_TOKEN }}
